function(create_project EXEC_NAME TYPE)
	create_project_with_alternate_folder_name(${EXEC_NAME} ${EXEC_NAME} ${TYPE})
endfunction()

function(create_project_with_alternate_folder_name EXEC_NAME OUTER_FOLDER_NAME TYPE)
	message("-- Building project ${EXEC_NAME}")
	
	file(GLOB_RECURSE SOURCE_FILES src/*.hpp src/*.cpp src/*.h src/*.c)
	
	if(${TYPE} STREQUAL "EXEC")
		add_executable(${EXEC_NAME} ${SOURCE_FILES})
	elseif(${TYPE} STREQUAL "LIBS")
		add_library(${EXEC_NAME} STATIC ${SOURCE_FILES})
	elseif(${TYPE} STREQUAL "LIBD")
		add_library(${EXEC_NAME} SHARED ${SOURCE_FILES})
	else()
		message(FATAL_ERROR "ERROR: Incorrectly specified project type! Type: ${TYPE} -- must be EXEC, LIBS, or LIBD. CMake will now exit.")
	endif()
	
	target_compile_definitions(${EXEC_NAME} PUBLIC _CRT_SECURE_NO_WARNINGS)
	target_compile_definitions(${EXEC_NAME} PUBLIC NOMINMAX)
	target_compile_definitions(${EXEC_NAME} PUBLIC HC_PROJECT_DIR="${HC_PROJECT_DIR}")
	
	target_include_directories(${EXEC_NAME} PUBLIC src)
	
	if(CMAKE_GENERATOR MATCHES "Visual Studio")
		message("-- Generating VS filters for ${EXEC_NAME}")
		create_filters(${OUTER_FOLDER_NAME} "${SOURCE_FILES}")
		message("-- Generating VS filters for ${EXEC_NAME} - done")
	endif()
	message("-- Building project ${EXEC_NAME} - done")
endfunction()

function(create_filters OUTER_FOLDER_NAME SOURCE_FILES)	
	foreach(_source IN ITEMS ${SOURCE_FILES})
		if (IS_ABSOLUTE "${_source}")
            file(RELATIVE_PATH _source_rel "${CMAKE_CURRENT_SOURCE_DIR}" "${_source}")
        else()
            set(_source_rel "${_source}")
        endif()
        get_filename_component(_source_path "${_source_rel}" PATH)
		string(REPLACE "src" "" _source_path_msvc "${_source_path}")
		string(REPLACE ${OUTER_FOLDER_NAME} "" _source_path_msvc "${_source_path_msvc}")
        string(REPLACE "/" "\\" _source_path_msvc "${_source_path_msvc}")
        source_group("${_source_path_msvc}" FILES "${_source}")
	endforeach()
endfunction()

function(link_core EXEC_NAME)
	message("-- Linking core directories to ${EXEC_NAME}")
	target_include_directories(${EXEC_NAME} PUBLIC "${CMAKE_SOURCE_DIR}/HellfireControl/src")
	target_link_libraries(${EXEC_NAME} PUBLIC HellfireCore)
	message("-- Linking core directories to ${EXEC_NAME} - done")
endfunction()

# Leave this here for now. Later on, it needs to be based on whether we're compiling OpenGL, Vulkan or DirectX
function(link_vulkan_sdk EXEC_NAME)
	message("-- Linking Vulkan SDK to ${EXEC_NAME}")
	if(WIN32)
		target_include_directories(${EXEC_NAME} PUBLIC $ENV{VULKAN_SDK}/Include/)
		target_link_directories(${EXEC_NAME} PUBLIC $ENV{VULKAN_SDK}/Lib/)
		target_link_libraries(${EXEC_NAME} PUBLIC vulkan-1.lib;slang.lib;spirv-cross-c.lib;dxcompiler.lib;comctl32.lib;propsys.lib;shlwapi.lib)
		
	else()
		message(FATAL_ERROR "ERROR: Linux and Mac not yet supported! Fix me or pester Owen!")
	endif()
	message("-- Linking Vulkan SDK to ${EXEC_NAME} - done")
endfunction()

function(link_vulkan_shader_comp EXEC_NAME)
	message("-- Linking Vulkan shader compilation tools to ${EXEC_NAME}")
	if(WIN32)
		target_link_libraries(${EXEC_NAME} PUBLIC slang.lib;spirv-cross-c.lib;dxcompiler.lib)
		target_link_libraries(${EXEC_NAME} PUBLIC
			$<$<CONFIG:Debug>:shaderc_combinedd.lib>
			$<$<CONFIG:Release>:shaderc_combined.lib>
		)
	else()
		message(FATAL_ERROR "ERROR: Linux and Mac not yet supported! Fix me or pester Owen!")
	endif()
	message("-- Linking Vulkan shader compilation tools to ${EXEC_NAME} - done")
endfunction()

function(move_working_directory_to_project_root EXEC_NAME)
	if(CMAKE_GENERATOR MATCHES "Visual Studio")
		set_property(TARGET ${EXEC_NAME} PROPERTY VS_DEBUGGER_WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}")
	endif()
endfunction()