
#include <HellfireControl/Render/RenderMemoryManager.hpp>

#if HC_USE_VULKAN
#include <Platform/Vulkan/VkRenderMemoryManager.hpp>
#include <Platform/Vulkan/VkRenderManager.hpp>

#define HC_VULKAN_PROTOTYPE_BUFFER_USAGE_BITS (VK_BUFFER_USAGE_VERTEX_BUFFER_BIT | VK_BUFFER_USAGE_INDEX_BUFFER_BIT | VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT | VK_BUFFER_USAGE_STORAGE_TEXEL_BUFFER_BIT | VK_BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT)

#endif