#pragma once

#include <HellfireControl/Core/Common.hpp>

enum HCShaderVarType : uint8_t {
	VAR_UNIFORM_BUFFER,
	VAR_STORAGE_BUFFER,
	VAR_STAGE_INPUT,
	VAR_STAGE_OUTPUT,
	VAR_COMBINED_IMAGE_SAMPLER,
	VAR_TEXTURE_2D,
	VAR_IMAGE_2D,
	VAR_SAMPLER,
	VAR_UNIFORM_TEXEL_BUFFER,
	VAR_STORAGE_TEXEL_BUFFER,
	VAR_PUSH_CONSTANT_BUFFER,
	VAR_SUBPASS_INPUT,
	VAR_BUILTIN_STAGE_INPUT,
	VAR_BUILTIN_STAGE_OUTPUT,
	VAR_ACCELERATION_STRUCTURE,
	VAR_SHADER_RECORD_BUFFER,
	VAR_ATOMIC_COUNTER,
	VAR_GL_PLAIN_UNIFORM
};

enum HCInputOutputType : uint16_t {
	IO_INVALID = 0,
	IO_BOOL = (1 << 2),
	IO_SIGNED_BYTE = (1 << 3),
	IO_UNSIGNED_BYTE = (1 << 4),
	IO_SIGNED_SHORT = (1 << 5),
	IO_UNSIGNED_SHORT = (1 << 6),
	IO_SIGNED_INT = (1 << 7),
	IO_UNSIGNED_INT = (1 << 8),
	IO_HALF_FLOAT = (1 << 9),
	IO_FLOAT = (1 << 10),
	IO_DOUBLE_FLOAT = (1 << 11),
	IO_MAX = 0xFFC
};

enum HCInterpolationType : uint16_t {
	INTERP_SMOOTH = 0,
	INTERP_FLAT = (1 << 12),
	INTERP_NO_PERSPECTIVE = (1 << 13),
	INTERP_CENTROID = (1 << 14),
	INTERP_SAMPLE = (1 << 15),
	INTERP_MAX = 0xF000
};

struct HCShaderVar {
	uint16_t m_u16Type = 0;
	uint16_t m_u16Flags = 0;
	uint32_t m_arrData[8];
};

struct HCShaderVarLabelEntry {
	std::string m_strVarName;
	uint32_t m_u32Index;
};

struct HCShaderVarTable {
	std::vector<HCShaderVarLabelEntry> m_vLabels;
	std::vector<HCShaderVar> m_vVars;
};

enum HCShaderFormat : uint8_t {
	SHADER_FORMAT_GLSL,
	SHADER_FORMAT_HLSL,
	SHADER_FORMAT_SLANG,
	SHADER_FORMAT_INVALID
};

enum HCShaderStageType : uint8_t {
	SHADER_STAGE_VERTEX,
	SHADER_STAGE_FRAGMENT,
	SHADER_STAGE_GEOMETRY,
	SHADER_STAGE_TESSELLATION_CONTROL,
	SHADER_STAGE_TESSELLATION_EVALUATION,
	SHADER_STAGE_COMPUTE,
	SHADER_STAGE_TASK,
	SHADER_STAGE_MESH,
	SHADER_STAGE_RAYGEN,
	SHADER_STAGE_ANY_HIT,
	SHADER_STAGE_CLOSEST_HIT,
	SHADER_STAGE_MISS,
	SHADER_STAGE_INTERSECTION,
	SHADER_STAGE_CALLABLE,
	SHADER_STAGE_INVALID
};