#!/usr/bin/env bash

pushd $1/src/HellfireControl
echo "// Automatically generated by CMake build script targeting Apple platforms" > ./module.modulemap
echo "module HellfireControl {" >> ./module.modulemap

for header in $(find . -name "*.hpp"); do
  echo "    header \"${header:2}\"" >> ./module.modulemap
done

echo "    export *" >> ./module.modulemap
echo "}" >> ./module.modulemap
popd